name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: npm run dist
      - run: npm pack -ws && tar -xzf scrapy-ui-*.tgz

      # publish to branch
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: ./package
          BRANCH: alpha
          COMMIT_NAME: "github-actions[bot]"
          COMMIT_EMAIL: "github-actions[bot]@users.noreply.github.com"

      # publish to npmjs.org
      - name: publish to npmjs.org
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm publish -ws
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  dockerhub:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Multi-platform build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set tags
        id: set-tags
        run: |
          if [[ "${{ github.ref }}" =~ ^refs/tags/v ]]; then
            echo "TAGS=dogegg/scrapy-ui:latest" >> "$GITHUB_OUTPUT"
          else
            echo "TAGS=dogegg/scrapy-ui:development" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.set-tags.outputs.TAGS }}
